services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: jenkins #user to run as on system
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - /etc/apps/jenkins:/var/jenkins_home