services:
  watchtower:
    image: nickfedor/watchtower:latest
    environment:
      WATCHTOWER_SCHEDULE: 0 0 02 * * *
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
networks: {}