services:
  broker:
    image: docker.io/library/redis:8
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - /etc/apps/paperlessngx/redis:/data
  db:
    image: docker.io/library/postgres:18
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - /etc/apps/paperlessngx/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: xxxxx
      POSTGRES_USER: xxxxxxx
      POSTGRES_PASSWORD: xxxxxx
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 1221:8000
    volumes:
      - /etc/apps/paperlessngx/app/data:/usr/src/paperless/data
      - /etc/apps/paperlessngx/app/media:/usr/src/paperless/media
      - /etc/apps/paperlessngx/app/export:/usr/src/paperless/export
      - /etc/apps/paperlessngx/app/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_OCR_PDF_A: false
      PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'
