services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=xxxxxx
      - PLEX_UID=1001
      - PLEX_GID=1001
    network_mode: host
    volumes:
      - /etc/plex/config:/config
      - /etc/plex/transcode:/transcode
      - /home/tv:/tv
      - /home/movies:/movies
      - /home/familyvids:/familyvids
      - /home/photos:/photos
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    network_mode: host
    volumes:
      - /etc/apps/homebridge:/homebridge
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 333:3000
    volumes:
      - /etc/apps/homepage:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /etc/apps/homebox:/data/
    ports:
      - 3100:7745
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: lubelogger
    restart: unless-stopped
    volumes:
      - /etc/apps/lubelogger/data:/App/data
      - /etc/apps/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 369:8080
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    restart: unless-stopped
    ports:
      - 3693:8080
    volumes:
      - /etc/apps/trilium:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro